const electionDate=new Date('2026-11-03T00:00:00-05:00');
const days=document.querySelector('[data-days]');
function updateCountdown(){days.textContent=Math.max(0,Math.ceil((electionDate-new Date())/86400000)).toLocaleString()} updateCountdown();setInterval(updateCountdown,60000);
const questions=[
 {topic:'Cost of living',text:'When prices and household costs are high, what should government prioritize?',options:['Lower taxes and regulation where they raise costs','Targeted help for households under the most pressure','More competition and supply in housing, energy, and goods','Spending restraint and lower public borrowing','I need more context']},
 {topic:'Healthcare',text:'What outcome matters most in healthcare policy?',options:['Lower premiums, bills, and prescription costs','Reliable access for everyone, even when they cannot pay','More private choice and competition among providers','Clear prices and accountability for public spending','I need more context']},
 {topic:'Immigration',text:'Which balance should immigration policy prioritize?',options:['Stronger border enforcement and faster removals under law','More legal pathways and a workable process for long-term residents','Due process, humane treatment, and limits on government power','Local capacity, employment rules, and public-safety enforcement','I need more context']},
 {topic:'Public safety and rights',text:'How should government balance public safety and individual rights?',options:['Give law enforcement more tools and resources','Prioritize prevention, treatment, and community services','Require stronger warrants, oversight, and due-process protections','Keep decisions close to local communities','I need more context']},
 {topic:'Education',text:'What should public education policy prioritize?',options:['Academic basics, testing, and measurable results','Parent choice among public, charter, private, or home options','More funding for teachers, services, and student needs','Local control over curriculum and school policy','I need more context']},
 {topic:'Government power and money',text:'What safeguard matters most when government acts or spends?',options:['Congressional authorization and clear limits on executive power','Balanced budgets, debt reduction, and spending transparency','Independent courts, inspectors, and public oversight','Emergency powers with short deadlines and renewal votes','I need more context']}
];
let current=0,answers={};try{const saved=JSON.parse(localStorage.getItem('represent-me-beliefs')||'{}');if(saved&&typeof saved==='object')answers=saved}catch{}
const dialog=document.querySelector('#dialog'),question=document.querySelector('#question'),next=document.querySelector('#next'),back=document.querySelector('#back');
function render(){const q=questions[current];question.innerHTML=`<p class="question-progress">Question ${current+1} of ${questions.length} · ${q.topic}</p><h2 class="question-copy">${q.text}</h2><div>${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[current]===i?'checked':''}> ${o}</label>`).join('')}</div>`;back.style.visibility=current?'visible':'hidden';next.textContent=current===questions.length-1?'Finish →':'Next →'}
document.querySelector('#start').addEventListener('click',()=>{current=0;render();dialog.showModal()});
next.addEventListener('click',()=>{const choice=document.querySelector('input[name=answer]:checked');if(!choice)return;answers[current]=Number(choice.value);if(current<questions.length-1){current++;render()}else{dialog.close();const save=window.confirm('Questionnaire complete. Save your general priorities on this device for next time? Your candidate selections are never saved.');if(save){localStorage.setItem('represent-me-beliefs',JSON.stringify(answers));document.querySelector('#beliefs-status').textContent='General priorities saved on this device. Voting choices are never saved.';document.querySelector('#start').textContent='Review questionnaire ✓'}else{localStorage.removeItem('represent-me-beliefs');document.querySelector('#beliefs-status').textContent='Answers not saved.'}}});
back.addEventListener('click',()=>{if(current){current--;render()}});
document.querySelector('#privacy').addEventListener('click',()=>document.querySelector('#privacy-dialog').showModal());

document.querySelector('#clear-beliefs').addEventListener('click',()=>{localStorage.removeItem('represent-me-beliefs');answers={};document.querySelector('#beliefs-status').textContent='Saved questionnaire answers cleared.';document.querySelector('#start').textContent='Take questionnaire →'});
